stages:
  - deploy

image: ${DOCKER_DEPLOY_IMAGE_NAME}:${DOCKER_DEPLOY_IMAGE_TAG}

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  STACK: confluent
  KSQL_UI_IMAGE_TAG: 0.0.1

deploy-ksql-server-supporting-branch-develop:
  stage: deploy
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_ksql-server
    IMAGE_TAG: ${DEV_CONFLUENT_VERSION}
    COMPOSE_FILE: docker-compose.ksql-server.tmpl.yml:docker-compose.ksql-server.dev.yml
  script:
    - deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE}
  environment:
    name: dev/ksql-server
  only:
    - branches
  except:
    - master
  when: manual

deploy-ksql-server-stable-branch-develop:
  stage: deploy
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_ksql-server
    IMAGE_TAG: ${DEV_CONFLUENT_VERSION}
    COMPOSE_FILE: docker-compose.ksql-server.tmpl.yml:docker-compose.ksql-server.dev.yml
  script:
    - deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE}
  environment:
    name: dev/ksql-server
  only:
    - master
  when: manual

deploy-ksql-server-supporting-branch-production:
  stage: deploy
  variables:
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_ksql-server
    IMAGE_TAG: ${PRO_CONFLUENT_VERSION}
    COMPOSE_FILE: docker-compose.ksql-server.tmpl.yml:docker-compose.ksql-server.prod.yml
  script:
    - deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE}
  environment:
    name: pro/ksql-server
  only:
    - branches
  except:
    - master
  when: manual

deploy-ksql-server-stable-branch-production:
  stage: deploy
  variables:
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_ksql-server
    IMAGE_TAG: ${PRO_CONFLUENT_VERSION}
    COMPOSE_FILE: docker-compose.ksql-server.tmpl.yml:docker-compose.ksql-server.prod.yml
  script:
    - deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE}
  environment:
    name: pro/ksql-server
  only:
    - master
  when: manual

deploy-ksql-ui-supporting-branch-develop:
  stage: deploy
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_ksql-ui
    IMAGE_TAG: ${KSQL_UI_IMAGE_TAG}
    COMPOSE_FILE: docker-compose.ksql-ui.tmpl.yml:docker-compose.ksql-ui.dev.yml
    PUBLIC_HOSTNAME: ${DEV_PUBLIC_HOSTNAME}
    UI_AUTH: ${DEV_UI_AUTH}
  script:
    - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH}
  environment:
    name: dev/ksql-ui
  only:
    - branches
  except:
    - master
  when: manual

deploy-ksql-ui-stable-branch-develop:
  stage: deploy
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_ksql-ui
    IMAGE_TAG: ${KSQL_UI_IMAGE_TAG}
    COMPOSE_FILE: docker-compose.ksql-ui.tmpl.yml:docker-compose.ksql-ui.dev.yml
    PUBLIC_HOSTNAME: ${DEV_PUBLIC_HOSTNAME}
    UI_AUTH: ${DEV_UI_AUTH}
  script:
     - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH}
  environment:
    name: dev/ksql-ui
  only:
    - master
  when: manual

deploy-ksql-ui-supporting-branch-production:
  stage: deploy
  variables:
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_ksql-ui
    IMAGE_TAG: ${KSQL_UI_IMAGE_TAG}
    COMPOSE_FILE: docker-compose.ksql-ui.tmpl.yml:docker-compose.ksql-ui.prod.yml
    PUBLIC_HOSTNAME: ${PRO_PUBLIC_HOSTNAME}
    UI_AUTH: ${PRO_UI_AUTH}
  script:
     - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH}
  environment:
    name: pro/ksql-ui
  only:
    - branches
  except:
    - master
  when: manual

deploy-ksql-ui-stable-branch-production:
  stage: deploy
  variables:
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_ksql-ui
    IMAGE_TAG: ${KSQL_UI_IMAGE_TAG}
    COMPOSE_FILE: docker-compose.ksql-ui.tmpl.yml:docker-compose.ksql-ui.prod.yml
    PUBLIC_HOSTNAME: ${PRO_PUBLIC_HOSTNAME}
    UI_AUTH: ${PRO_UI_AUTH}
  script:
     - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH}
  environment:
    name: pro/ksql-ui
  only:
    - master
  when: manual
